package com.directi.train.tweetapp;

import org.apache.commons.dbcp.BasicDataSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.simple.SimpleJdbcTemplate;

@Configuration
public class AppConfig {
    @Bean
    public SimpleJdbcTemplate simpleJdbcTemplate() {
        BasicDataSource dataSource = new BasicDataSource();
        dataSource.setUrl("jdbc:hsqldb:mem:miniTwitter");
        dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
        SimpleJdbcTemplate db = new SimpleJdbcTemplate(dataSource);
        db.update("CREATE TABLE follows (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY," +
                "user_id INTEGER NOT NULL," +
                "follower_id INTEGER NOT NULL," +
                ")");
        db.update("CREATE TABLE todos (" +
                  "id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY," +
                  "user_id INTEGER NOT NULL," +
                  "receiver_id INTEGER NOT NULL," +
                  "description varchar(128) DEFAULT '' NOT NULL" +
                  ")");
        db.update("CREATE TABLE users (" +
                  "id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY," +
                  "username varchar(128) NOT NULL," +
                  "email varchar(128) NOT NULL," +
                  "password varchar(128) NOT NULL" +
                  ")");
        return db;
    }

    @Bean
    public ThreadLocal<Long> userID() {
        return new ThreadLocal<Long>();
    }
}
